#! /bin/bash

LR="$HOME/.local"
BRANCHNAME="mpich"
DEST="mpich-dev"

usage() {
    echo "Tools to delete MPICH branch"
    echo "clean-mpich-branch branch-name"
}

delete_dir() {
    if [[ -d "./$1" ]]; then
        echo "Deleting $1"
        rm -rf "./$1"
    fi
    if [[ -d "$LR/$DEST/$1" ]]; then
        echo "Deleting $LR/$DEST/$1"
        rm -rf "$LR/$DEST/$1"
    fi
}

if [[ $1 == "" ]]; then
    # list all available
    usage
    exit 0
else
    BRANCHNAME=$1
    delete_dir "$BRANCHNAME"
fi

