#! /bin/bash

LIBNAME='mpich'

if [[ $1 == "" ]]; then
    # list all available
    echo "Current MPI: $(readlink "$LR/mpi")"
    find "$LR/mpich" -maxdepth 1 | sed -e 's/\.\///' | grep --color=auto "mpich/"
    find "$LR/mpich-dev" -maxdepth 1 | sed -e 's/\.\///' | grep --color=auto "mpich-dev/"
    exit 0
else
    LIBNAME=$1
fi

if [[ -d $LR/$LIBNAME ]]; then
    unlink "$LR/mpi"
    ln -s "$LIBNAME" "$LR/mpi"
    readlink "$LR/mpi"
fi
