#! /bin/bash

LIBNAME='mpich'

if [[ $1 == "" ]]; then
    # list all available
    echo "Current MPI: $(readlink "$LR/mpi/current")"
    find "$LR/mpi" -maxdepth 1 -type d
    exit 0
else
    LIBNAME=$1
fi

if [[ -d $LR/mpi/$LIBNAME ]]; then
    unlink "$LR/mpi/current"
    ln -s "$LIBNAME" "$LR/mpi/current"
else
    echo "MPI installation: $LIBNAME does not exist"
fi
echo "Current MPI: $(readlink "$LR/mpi/current")"
